# Generated by Django 3.1.7 on 2021-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aliens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='matches',
            field=models.IntegerField(default=0),
        ),
    ]
