# Generated by Django 3.1.7 on 2021-04-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_aliens', '0004_auto_20210405_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='users',
            new_name='user',
        ),
    ]
